# Generated by Django 4.0.4 on 2022-08-16 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLOR', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('black', 'black'), ('orange', 'orange'), ('purple', 'purple'), ('white', 'white'), ('gold', 'gold'), ('indigo', 'indigo'), ('brown', 'brown'), ('yellow', 'yellow'), ('grey', 'grey'), ('dark red', 'dark red'), ('turquoise', 'turquoise'), ('lavender', 'lavender'), ('blue', 'blue')], default='red', max_length=200, null=True)),
                ('full_size', models.CharField(choices=[('Xlarge', 'Xlarge'), ('large', 'large'), ('medium', 'medium'), ('slimfit', 'slimfit')], default='', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('more_info', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Mono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200, null=True)),
                ('types', models.CharField(max_length=200, null=True)),
                ('others', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('COLOR', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('black', 'black'), ('orange', 'orange'), ('purple', 'purple'), ('white', 'white'), ('gold', 'gold'), ('indigo', 'indigo'), ('brown', 'brown'), ('yellow', 'yellow'), ('grey', 'grey'), ('dark red', 'dark red'), ('turquoise', 'turquoise'), ('lavender', 'lavender'), ('blue', 'blue')], default='red', max_length=200, null=True)),
                ('full_size', models.FloatField(default='0', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('more_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.customer')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.entry')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.entry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.mono')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ity.mono'),
        ),
    ]
