# Generated by Django 5.0.3 on 2024-04-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ity', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mono',
            name='cloth_type',
            field=models.CharField(choices=[('Gown', 'Gown'), ('Shirt', 'Shirt')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mono',
            name='COLOR',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red'), ('black', 'black'), ('orange', 'orange'), ('purple', 'purple'), ('white', 'white'), ('gold', 'gold'), ('indigo', 'indigo'), ('brown', 'brown'), ('yellow', 'yellow'), ('grey', 'grey'), ('dark red', 'dark red'), ('turquoise', 'turquoise'), ('lavender', 'lavender'), ('blue', 'blue')], default='red', max_length=200),
        ),
    ]
