# Generated by Django 5.0.3 on 2024-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ity', '0003_mono_cloth_type_alter_mono_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mono',
            name='cloth_type',
            field=models.CharField(choices=[('Gown', 'Gown'), ('Shirt', 'Shirt'), ('Monogramming', 'Monogramming'), ('Dress', 'Dress'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Accessories', 'Accessories'), ('Trouser', 'Trouser'), ('Customize', 'Customize')], max_length=200, null=True),
        ),
    ]
